/** 菜单常用 Iconify 图标（Remix Icon） */
export const MENU_ICON_PRESETS = [
  'ri:settings-3-line',
  'ri:user-line',
  'ri:shield-user-line',
  'ri:menu-line',
  'ri:folder-line',
  'ri:article-line',
  'ri:file-list-3-line',
  'ri:dashboard-line',
  'ri:home-line',
  'ri:lock-line',
  'ri:key-line',
  'ri:team-line',
  'ri:group-line',
  'ri:shopping-bag-line',
  'ri:store-line',
  'ri:bar-chart-line',
  'ri:pie-chart-line',
  'ri:notification-line',
  'ri:mail-line',
  'ri:image-line',
  'ri:video-line',
  'ri:tools-line',
  'ri:database-line',
  'ri:cloud-line',
] as const
